export const dados_lanches = [
    {  
        image: '../public/assets/food1.png',
        category: 1,
        alt_image:'Imagem de um hamburguer',
        title_itens: 'Big Burge',
        descrition_from_itens: '2 hamburguer, alface, cebola, pliques e um pão com gergilim',
        price: '7,59',
        id: '1',
    },
    {  
        image: '../public/assets/food1.png',
        alt_image:'Imagem de um hamburguer',
        category: 1,
        title_itens: 'Big Salada',
        descrition_from_itens: '2 hamburguer, alface, cebola, pliques e um pão com gergilim',
        price: '7,59',
        id: '2',
    },
    {  
        image: '../public/assets/food1.png',
        alt_image:'Imagem de um hamburguer',
        category: 1,
        title_itens: 'Quatro queijos',
        descrition_from_itens: '2 hamburguer, alface, cebola, pliques e um pão com gergilim',
        price: '7,59',
        id: '3',
    }, 
    {  
        image: '../public/assets/food1.png',
        alt_image:'Imagem de um hamburguer',
        category: 2,
        title_itens: 'Big Burguer',
        descrition_from_itens: '2 hamburguer, alface, cebola, pliques e um pão com gergilim',
        price: '7,59',
        id: '4',
    }, 
    {  
        image: '../public/assets/food1.png',
        alt_image:'Imagem de um hamburguer',
        category: 3,
        title_itens: 'Big Burguer',
        descrition_from_itens: '2 hamburguer, alface, cebola, pliques e um pão com gergilim',
        price: '7,59',
        id: '5',
    }, 
    {  
        image: '../public/assets/food1.png',
        alt_image:'Imagem de um hamburguer',
        category: 1,
        title_itens: 'Big Burguer',
        descrition_from_itens: '2 hamburguer, alface, cebola, pliques e um pão com gergilim',
        price: '7,59',
        id: '6',
    },
    {  
        image: '../public/assets/food1.png',
        alt_image:'Imagem de um hamburguer',
        category: 4,
        title_itens: 'Big Burguer',
        descrition_from_itens: '2 hamburguer, alface, cebola, pliques e um pão com gergilim',
        price: '7,59',
        id: '7',
    },
    {  
        image: '../public/assets/food1.png',
        alt_image:'Imagem de um hamburguer',
        category: 1,
        title_itens: 'Big Burguer',
        descrition_from_itens: '2 hamburguer, alface, cebola, pliques e um pão com gergilim',
        price: '7,59',
        id: '8',
    },  
]
